[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer_runs = 100_000
fuzz = { runs = 512 }
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = false

[profile.ci]
fuzz = { runs = 2500 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
